#!/usr/bin/env python3
# Build Task Manger project
# Done by : Nadia Ahmed
from flask import Flask, render_template, request
from flask import redirect, jsonify, url_for, flash
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy import exists
from database_setup import TaskItem, Base, Task, User
from flask import session as login_session


app = Flask(__name__)
engine = create_engine('sqlite:///taskitem.db')
Base.metadata.bind = engine

DBSession = sessionmaker(bind=engine)
session = DBSession()

# Show main page 
@app.route('/')
def mainPage():
	return render_template('mainPage.html')

# Show All Task page 
@app.route('/Task')
def showTask():
	return render_template('showTask.html')

# Add Task page 
@app.route('/addTask')
def addTask():
	return render_template('addTask.html')

# Edit Task page 
@app.route('/editTask')
def editTask():
	return render_template('editTask.html')

# Edit Task page 
@app.route('/deleteTask')
def deleteTask():
	return render_template('deleteTask.html')

if __name__ == '__main__':
    app.secret_key = 'super_secret_key'
    app.debug = True
    app.run(host='0.0.0.0', port=8000, threaded=False)